import { AppShell } from '@/next-app-pages';
import { createServerDbClient, ServerDbClients } from '@/node-supabase';
import { redirect } from 'next/navigation';
import { NAV } from '../../config/app/nav';
import { BRAND } from '../../config/brand';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function AppLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerDbClient(ServerDbClients.ServerComponent);

  const {
    data: { session },
  } = await supabase.auth.getSession();
  if (!session) redirect('/auth/sign-in');
  const { data: user, error } = await supabase
    .from('users')
    .select('*')
    .eq('id', session.user.id)
    .single();

  console.log({ user, error });
  // if (user && !user.admin_role)
  //   return <SystemMessageHero {...adminAccessDenied} />;

  return (
    <AppShell brand={BRAND} navItems={NAV}>
      {children}
    </AppShell>
  );
}
