import { AppShell } from '@/next-app-pages';
import { NAV } from '../../config/app/nav';
import { BRAND } from '../../config/brand';
import '../global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function AppLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const supabase = createServerDbClient(ServerDbClients.ServerComponent);

  // const {
  //   data: { session },
  // } = await supabase.auth.getSession();
  // if (!session) redirect('/auth/signin');
  // const { data: user, error } = await supabase
  //   .from('users')
  //   .select('*')
  //   .eq('id', session.user.id)
  //   .single();

  // console.log({ user, error });
  // if (user && !user.admin_role)
  //   return <SystemMessageHero {...adminAccessDenied} />;

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppShell brand={BRAND} navItems={NAV}>
          {children}
        </AppShell>
      </body>
    </html>
  );
}
