import { AppShell } from '@/next-app-pages';
import { NAV } from '../../config/app/nav';
import { BRAND } from '../../config/brand';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppShell brand={BRAND} navItems={NAV}>
      {children}
    </AppShell>
  );
}
