
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function AppLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
