import { AuthShell } from '@/next-auth-pages';
import '../global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AuthShell>{children}</AuthShell>
      </body>
    </html>
  );
}
