export * from './about/about';
export * from './benefits/benefits';
export * from './blog/blog';
export * from './case-studies/case-studies';
export * from './cta-banner/cta-banner';
export * from './cta-form/cta-form';
export * from './faqs/faqs';
export * from './features/features';
export * from './google-map/google-map';
export * from './how-it-works/how-it-works';
export * from './pricing/pricing';
export * from './products/products';
export * from './try-product-stepper/try-product-stepper';
// export * from './team/team';
